pipeline:
  preview: 
    image: registry.webix.io/js-build-env
    pull: true
    when:
      event: push
      branch:
        exclude: release
    secrets: [ preview_hook_token, aws_access_key_id, aws_secret_access_key ]
    commands:
      - yarn install --pure-lockfile
      - yarn build
      - /bin/bash ./deploy.sh

  release: 
    image: registry.webix.io/js-build-env
    pull: true
    when:
      event: push
      branch: release
    secrets: [ deploy_hook_token, aws_access_key_id, aws_secret_access_key ]
    commands:
      - yarn install --pure-lockfile
      - yarn standalone
      - /bin/bash ./deploy.sh
